#!/bin/bash

files=$(sudo find / -user os155 ! -path '/proc*' ! -name '.*' -mmin -60)
tar -cvpzf backup.tar.gz --exclude=tmp $files


echo "Your Files and Directories in your computer has been already Backed-Up"


# See README for crontab 
# PINK TEAM
