#!/bin/bash
tar -cf backup.tar pinkteamscript
file=$(find /home -user ubuntu ! -path '/proc*' ! -name '.*' -mmin -60)
for i in $file 
do
   echo $i
   a=$(ls -l $i|grep 'ubuntu'|awk -F ' ' '{print$3}') 
   if [[ $a == 'ubuntu' ]];
    then
      echo $i
      tar -rf backup.tar $i
    
   fi
done

echo "Your Files and Directories has been Backed-Up"


# See README for crontab 
# PINK TEAM
